POST http://localhost:3001/api/elements
Content-Type: application/json

{
    "name": "Hydrogen",
    "z": "1",
    "am": "1.008",
    "symbol": "H"
    }


###
GET http://localhost:3001/api/elements/H