const Element = require("../models/element");
let localElements = [
  {
    name: "Hydrogen",
    z: "1",
    am: "1.008",
    isotopes: "<sup>1</sup>H,  <sup>2</sup>H",
    symbol: "H",
  },
  {
    name: "Helium",
    z: "2",
    am: "4.003",
    isotopes: "<sup>4</sup>He",
    symbol: "He",
  },
  {
    name: "Lithium",
    z: "3",
    am: "6.94",
    isotopes: "<sup>7</sup>Li",
    symbol: "Li",
  },
  {
    name: "Beryllium",
    z: "4",
    am: "9.012",
    isotopes: "<sup>9</sup>Be",
    symbol: "Be",
  },
  {
    name: "Boron",
    z: "5",
    am: "10.81",
    isotopes: "<sup>11</sup>B",
    symbol: "B",
  },
  {
    name: "Carbon",
    z: "6",
    am: "12.011",
    isotopes: "<sup>12</sup>C,  <sup>13</sup>C,  <sup>14</sup>C",
    symbol: "C",
  },
  {
    name: "Nitrogen",
    z: "7",
    am: "14.007",
    isotopes: "<sup>14</sup>N",
    symbol: "N",
  },
  {
    name: "Oxygen",
    z: "8",
    am: "15.999",
    isotopes: "<sup>16</sup>O",
    symbol: "O",
  },
  {
    name: "Fluorine",
    z: "9",
    am: "18.998",
    isotopes: "<sup>19</sup>F",
    symbol: "F",
  },
  {
    name: "Neon",
    z: "10",
    am: "20.180",
    isotopes: "<sup>20</sup>Ne",
    symbol: "Ne",
  },
  {
    name: "Sodium",
    z: "11",
    am: "22.990",
    isotopes: "<sup>23</sup>Na",
    symbol: "Na",
  },
  {
    name: "Magnesium",
    z: "12",
    am: "24.305",
    isotopes: "<sup>24</sup>Mg",
    symbol: "Mg",
  },
  {
    name: "Aluminium",
    z: "13",
    am: "26.982",
    isotopes: "<sup>27</sup>Al",
    symbol: "Al",
  },
  {
    name: "Silicon",
    z: "14",
    am: "28.085",
    isotopes: "<sup>28</sup>Si,  <sup>30</sup>Si",
    symbol: "Si",
  },
  {
    name: "Phosphorus",
    z: "15",
    am: "30.974",
    isotopes: "<sup>31</sup>P",
    symbol: "P",
  },
  {
    name: "Sulfur",
    z: "16",
    am: "32.06",
    isotopes: "<sup>32</sup>S",
    symbol: "S",
  },
  {
    name: "Chlorine",
    z: "17",
    am: "35.45",
    isotopes: "<sup>35</sup>Cl,  <sup>37</sup>Cl",
    symbol: "Cl",
  },
  {
    name: "Argon",
    z: "18",
    am: "39.95",
    isotopes: "<sup>40</sup>Ar",
    symbol: "Ar",
  },
  {
    name: "Potassium",
    z: "19",
    am: "39.098",
    isotopes: "<sup>39</sup>K",
    symbol: "K",
  },
  {
    name: "Calcium",
    z: "20",
    am: "40.078",
    isotopes: "<sup>40</sup>Ca",
    symbol: "Ca",
  },
  {
    name: "Scandium",
    z: "21",
    am: "44.956",
    isotopes: "<sup>45</sup>Sc",
    symbol: "Sc",
  },
  {
    name: "Titanium",
    z: "22",
    am: "47.867",
    isotopes: "<sup>48</sup>Ti",
    symbol: "Ti",
  },
  {
    name: "Vanadium",
    z: "23",
    am: "50.942",
    isotopes: "<sup>51</sup>V",
    symbol: "V",
  },
  {
    name: "Chromium",
    z: "24",
    am: "51.996",
    isotopes: "<sup>52</sup>Cr",
    symbol: "Cr",
  },
  {
    name: "Manganese",
    z: "25",
    am: "54.938",
    isotopes: "<sup>55</sup>Mn",
    symbol: "Mn",
  },
  {
    name: "Iron",
    z: "26",
    am: "55.845",
    isotopes: "<sup>56</sup>Fe",
    symbol: "Fe",
  },
  {
    name: "Cobalt",
    z: "27",
    am: "58.933",
    isotopes: "<sup>59</sup>Co",
    symbol: "Co",
  },
  {
    name: "Nickel",
    z: "28",
    am: "58.693",
    isotopes: "<sup>58</sup>Ni",
    symbol: "Ni",
  },
  {
    name: "Copper",
    z: "29",
    am: "63.546",
    isotopes: "<sup>63</sup>Cu",
    symbol: "Cu",
  },
  {
    name: "Zinc",
    z: "30",
    am: "65.38",
    isotopes: "<sup>64</sup>Zn",
    symbol: "Zn",
  },
  {
    name: "Gallium",
    z: "31",
    am: "69.723",
    isotopes: "<sup>69</sup>Ga",
    symbol: "Ga",
  },
  {
    name: "Germanium",
    z: "32",
    am: "72.630",
    isotopes: "<sup>73</sup>Ge,  <sup>74</sup>Ge",
    symbol: "Ge",
  },
  {
    name: "Arsenic",
    z: "33",
    am: "74.922",
    isotopes: "<sup>75</sup>As",
    symbol: "As",
  },
  {
    name: "Selenium",
    z: "34",
    am: "78.971",
    isotopes: "<sup>80</sup>Se",
    symbol: "Se",
  },
  {
    name: "Bromine",
    z: "35",
    am: "79.904",
    isotopes: "<sup>79</sup>Br",
    symbol: "Br",
  },
  {
    name: "Krypton",
    z: "36",
    am: "83.798",
    isotopes: "<sup>84</sup>Kr",
    symbol: "Kr",
  },
  {
    name: "Rubidium",
    z: "37",
    am: "85.468",
    isotopes: "<sup>85</sup>Rb,  <sup>87</sup>Rb",
    symbol: "Rb",
  },
  {
    name: "Strontium",
    z: "38",
    am: "87.62",
    isotopes: "<sup>86</sup>Sr,  <sup>87</sup>Sr,  <sup>88</sup>Sr",
    symbol: "Sr",
  },
  {
    name: "Yttrium",
    z: "39",
    am: "88.906",
    isotopes: "<sup>89</sup>Y",
    symbol: "Y",
  },
  {
    name: "Zirconium",
    z: "40",
    am: "91.224",
    isotopes: "<sup>90</sup>Zr,  <sup>92</sup>Zr,  <sup>94</sup>Zr",
    symbol: "Zr",
  },
  {
    name: "Niobium",
    z: "41",
    am: "92.906",
    isotopes: "<sup>93</sup>Nb",
    symbol: "Nb",
  },
  {
    name: "Molybdenum",
    z: "42",
    am: "95.95",
    isotopes: "<sup>95</sup>Mo,  <sup>96</sup>Mo,  <sup>98</sup>Mo",
    symbol: "Mo",
  },
  {
    name: "Technetium",
    z: "43",
    am: "[98]",
    isotopes: "",
    symbol: "Tc",
  },
  {
    name: "Ruthenium",
    z: "44",
    am: "101.07",
    isotopes: "<sup>101</sup>Ru,  <sup>102</sup>Ru,  <sup>104</sup>Ru",
    symbol: "Ru",
  },
  {
    name: "Rhodium",
    z: "45",
    am: "102.906",
    isotopes: "<sup>103</sup>Rh",
    symbol: "Rh",
  },
  {
    name: "Palladium",
    z: "46",
    am: "106.42",
    isotopes: "<sup>106</sup>Pd",
    symbol: "Pd",
  },
  {
    name: "Silver",
    z: "47",
    am: "107.868",
    isotopes: "<sup>107</sup>Ag",
    symbol: "Ag",
  },
  {
    name: "Cadmium",
    z: "48",
    am: "112.414",
    isotopes: "<sup>114</sup>Cd",
    symbol: "Cd",
  },
  {
    name: "Indium",
    z: "49",
    am: "114.818",
    isotopes: "<sup>115</sup>In",
    symbol: "In",
  },
  {
    name: "Tin",
    z: "50",
    am: "118.710",
    isotopes: "<sup>120</sup>Sn",
    symbol: "Sn",
  },
  {
    name: "Antimony",
    z: "51",
    am: "121.760",
    isotopes: "<sup>121</sup>Sb",
    symbol: "Sb",
  },
  {
    name: "Tellurium",
    z: "52",
    am: "127.60",
    isotopes: "<sup>130</sup>Te",
    symbol: "Te",
  },
  {
    name: "Iodine",
    z: "53",
    am: "126.904",
    isotopes: "<sup>127</sup>I",
    symbol: "I",
  },
  {
    name: "Xenon",
    z: "54",
    am: "131.293",
    isotopes: "<sup>132</sup>Xe",
    symbol: "Xe",
  },
  {
    name: "Caesium",
    z: "55",
    am: "132.905",
    isotopes: "<sup>133</sup>Cs",
    symbol: "Cs",
  },
  {
    name: "Barium",
    z: "56",
    am: "137.327",
    isotopes: "<sup>138</sup>Ba",
    symbol: "Ba",
  },
  {
    name: "Lanthanum",
    z: "57",
    am: "138.905",
    isotopes: "<sup>139</sup>La",
    symbol: "La",
  },
  {
    name: "Hafnium",
    z: "72",
    am: "178.486",
    isotopes: "<sup>177</sup>Hf,  <sup>178</sup>Hf,  <sup>180</sup>Hf",
    symbol: "Hf",
  },
  {
    name: "Tantalum",
    z: "73",
    am: "180.948",
    isotopes: "<sup>180</sup>Ta,  <sup>181</sup>Ta",
    symbol: "Ta",
  },
  {
    name: "Tungsten",
    z: "74",
    am: "183.84",
    isotopes: "<sup>182</sup>W,  <sup>184</sup>W,  <sup>186</sup>W",
    symbol: "W",
  },
  {
    name: "Rhenium",
    z: "75",
    am: "186.207",
    isotopes: "<sup>187</sup>Re",
    symbol: "Re",
  },
  {
    name: "Osmium",
    z: "76",
    am: "190.23",
    isotopes: "<sup>192</sup>Os",
    symbol: "Os",
  },
  {
    name: "Iridium",
    z: "77",
    am: "192.217",
    isotopes: "<sup>193</sup>Ir",
    symbol: "Ir",
  },
  {
    name: "Platinum",
    z: "78",
    am: "195.084",
    isotopes: "<sup>195</sup>Pt",
    symbol: "Pt",
  },
  {
    name: "Gold",
    z: "79",
    am: "196.967",
    isotopes: "<sup>197</sup>Au",
    symbol: "Au",
  },
  {
    name: "Mercury",
    z: "80",
    am: "200.592",
    isotopes: "<sup>202</sup>Hg",
    symbol: "Hg",
  },
  {
    name: "Thallium",
    z: "81",
    am: "204.38",
    isotopes: "<sup>205</sup>Tl",
    symbol: "Tl",
  },
  {
    name: "Lead",
    z: "82",
    am: "207.2",
    isotopes: "<sup>208</sup>Pb",
    symbol: "Pb",
  },
  {
    name: "Bismuth",
    z: "83",
    am: "208.980",
    isotopes: "<sup>209</sup>Bi",
    symbol: "Bi",
  },
  {
    name: "Polonium",
    z: "84",
    am: "[209]",
    isotopes: "<sup>209</sup>Po,  <sup>210</sup>Po",
    symbol: "Po",
  },
  {
    name: "Astatine",
    z: "85",
    am: "[210]",
    isotopes: "<sup>210</sup>At,  <sup>211</sup>At",
    symbol: "At",
  },
  {
    name: "Radon",
    z: "86",
    am: "[222]",
    isotopes: "<sup>211</sup>Rn,  <sup>220</sup>Rn,  <sup>222</sup>Rn",
    symbol: "Rn",
  },
  {
    name: "Francium",
    z: "87",
    am: "[223]",
    isotopes: "<sup>223</sup>Fr",
    symbol: "Fr",
  },
  {
    name: "Radium",
    z: "88",
    am: "[226]",
    isotopes: "<sup>226</sup>Ra",
    symbol: "Ra",
  },
  {
    name: "Actinium",
    z: "89",
    am: "[227]",
    isotopes: "<sup>227</sup>Ac",
    symbol: "Ac",
  },
  {
    name: "Rutherfordium",
    z: "104",
    am: "[267]",
    isotopes: "<sup>265</sup>Rf",
    symbol: "Rf",
  },
  {
    name: "Dubnium",
    z: "105",
    am: "[268]",
    isotopes: "<sup>268</sup>Db",
    symbol: "Db",
  },
  {
    name: "Seaborgium",
    z: "106",
    am: "[269]",
    isotopes: "<sup>271</sup>Sg",
    symbol: "Sg",
  },
  {
    name: "Bohrium",
    z: "107",
    am: "[270]",
    isotopes: "<sup>272</sup>Bh",
    symbol: "Bh",
  },
  {
    name: "Hassium",
    z: "108",
    am: "[269]",
    isotopes: "<sup>270</sup>Hs",
    symbol: "Hs",
  },
  {
    name: "Meitnerium",
    z: "109",
    am: "[278]",
    isotopes: "<sup>276</sup>Mt",
    symbol: "Mt",
  },
  {
    name: "Darmstadtium",
    z: "110",
    am: "[281]",
    isotopes: "<sup>281</sup>Ds",
    symbol: "Ds",
  },
  {
    name: "Roentgenium",
    z: "111",
    am: "[280]",
    isotopes: "<sup>280</sup>Rg",
    symbol: "Rg",
  },
  {
    name: "Copernicium",
    z: "112",
    am: "[285]",
    isotopes: "<sup>285</sup>Cn",
    symbol: "Cn",
  },
  {
    name: "Nihonium",
    z: "113",
    am: "[286]",
    isotopes: "<sup>286</sup>Nh",
    symbol: "Nh",
  },
  {
    name: "Flerovium",
    z: "114",
    am: "[289]",
    isotopes: "<sup>289</sup>Fl",
    symbol: "Fl",
  },
  {
    name: "Moscovium",
    z: "115",
    am: "[289]",
    isotopes: "<sup>289</sup>Mc",
    symbol: "Mc",
  },
  {
    name: "Livermorium",
    z: "116",
    am: "[293]",
    isotopes: "<SUP>293</SUP>Lv",
    symbol: "Lv",
  },
  {
    name: "Tennessine",
    z: "117",
    am: "[294]",
    isotopes: "<sup>294</sup>Ts",
    symbol: "Ts",
  },
  {
    name: "Oganesson",
    z: "118",
    am: "[294]",
    isotopes: "<sup>294</sup>Og",
    symbol: "Og",
  },
  {
    name: "Cerium",
    z: "58",
    am: "140.116",
    isotopes: "<sup>140</sup>Ce",
    symbol: "Ce",
  },
  {
    name: "Praseodymium",
    z: "59",
    am: "140.908",
    isotopes: "<sup>141</sup>Pr",
    symbol: "Pr",
  },
  {
    name: "Neodymium",
    z: "60",
    am: "144.242",
    isotopes: "<sup>142</sup>Nd",
    symbol: "Nd",
  },
  {
    name: "Promethium",
    z: "61",
    am: "[145]",
    isotopes: "<sup>145</sup>Pm,  <sup>147</sup>Pm",
    symbol: "Pm",
  },
  {
    name: "Samarium",
    z: "62",
    am: "150.36",
    isotopes: "<sup>152</sup>Sm",
    symbol: "Sm",
  },
  {
    name: "Europium",
    z: "63",
    am: "151.964",
    isotopes: "<sup>153</sup>Eu",
    symbol: "Eu",
  },
  {
    name: "Gadolinium",
    z: "64",
    am: "157.25",
    isotopes: "<sup>158</sup>Gd",
    symbol: "Gd",
  },
  {
    name: "Terbium",
    z: "65",
    am: "158.925",
    isotopes: "<sup>159</sup>Tb",
    symbol: "Tb",
  },
  {
    name: "Dysprosium",
    z: "66",
    am: "162.500",
    isotopes: "<sup>164</sup>Dy",
    symbol: "Dy",
  },
  {
    name: "Holmium",
    z: "67",
    am: "164.930",
    isotopes: "<sup>165</sup>Ho",
    symbol: "Ho",
  },
  {
    name: "Erbium",
    z: "68",
    am: "167.259",
    isotopes: "<sup>166</sup>Er",
    symbol: "Er",
  },
  {
    name: "Thulium",
    z: "69",
    am: "168.934",
    isotopes: "<sup>169</sup>Tm",
    symbol: "Tm",
  },
  {
    name: "Ytterbium",
    z: "70",
    am: "173.045",
    isotopes: "<sup>172</sup>Yb,  <sup>173</sup>Yb,  <sup>174</sup>Yb",
    symbol: "Yb",
  },
  {
    name: "Lutetium",
    z: "71",
    am: "174.967",
    isotopes: "<sup>175</sup>Lu",
    symbol: "Lu",
  },
  {
    name: "Thorium",
    z: "90",
    am: "232.038",
    isotopes: "<sup>230</sup>Th,  <sup>232</sup>Th",
    symbol: "Th",
  },
  {
    name: "Protactinium",
    z: "91",
    am: "231.036",
    isotopes: "<sup>231</sup>Pa",
    symbol: "Pa",
  },
  {
    name: "Uranium",
    z: "92",
    am: "238.029",
    isotopes: "<sup>234</sup>U,  <sup>235</sup>U,  <sup>238</sup>U",
    symbol: "U",
  },
  {
    name: "Neptunium",
    z: "93",
    am: "[237]",
    isotopes: "<sup>237</sup>Np",
    symbol: "Np",
  },
  {
    name: "Plutonium",
    z: "94",
    am: "[244]",
    isotopes: "<sup>238</sup>Pu,  <sup>239</sup>Pu,  <sup>240</sup>Pu",
    symbol: "Pu",
  },
  {
    name: "Americium",
    z: "95",
    am: "[243]",
    isotopes: "<sup>241</sup>Am,  <sup>243</sup>Am",
    symbol: "Am",
  },
  {
    name: "Curium",
    z: "96",
    am: "[247]",
    isotopes: "<sup>243</sup>Cm,  <sup>248</sup>Cm",
    symbol: "Cm",
  },
  {
    name: "Berkelium",
    z: "97",
    am: "[247]",
    isotopes: "<sup>247</sup>Bk,  <sup>249</sup>Bk",
    symbol: "Bk",
  },
  {
    name: "Californium",
    z: "98",
    am: "[251]",
    isotopes: "<sup>249</sup>Cf,  <sup>252</sup>Cf",
    symbol: "Cf",
  },
  {
    name: "Einsteinium",
    z: "99",
    am: "[252]",
    isotopes: "<sup>252</sup>Es",
    symbol: "Es",
  },
  {
    name: "Fermium",
    z: "100",
    am: "[257]",
    isotopes: "<sup>257</sup>Fm",
    symbol: "Fm",
  },
  {
    name: "Mendelevium",
    z: "101",
    am: "[258]",
    isotopes: "<sup>258</sup>Md,  <sup>260</sup>Md",
    symbol: "Md",
  },
  {
    name: "Nobelium",
    z: "102",
    am: "[259]",
    isotopes: "<sup>259</sup>No",
    symbol: "No",
  },
  {
    name: "Lawrencium",
    z: "103",
    am: "[262]",
    isotopes: "<sup>262</sup>Lr",
    symbol: "Lr",
  },
];

const elementsInDb = async () => {
  const elements = await Element.find({});
 // console.log("HELPER: Size of DB", elements.length);
  return elements.map((e) => e.toJSON());
};

module.exports = {
  localElements,
  elementsInDb,
};
